// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWogQPWmLHWy-Ab0zudtya_7e1pYrnkhA',
    appId: '1:925046371887:web:777fe6b615a477af4178da',
    messagingSenderId: '925046371887',
    projectId: 'translato-ac737',
    authDomain: 'translato-ac737.firebaseapp.com',
    storageBucket: 'translato-ac737.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF81NIL-Lj9XZ7uNQrbxDtQprHp6AhfLg',
    appId: '1:1065930327203:android:72999f72ee83c713002b16',
    messagingSenderId: '1065930327203',
    projectId: 'viveka-a4c04',
    storageBucket: 'viveka-a4c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTtYmGaU1V67UoLvoZpiKcBUz6ECeCgLI',
    appId: '1:925046371887:ios:c8080c2d64198d8b4178da',
    messagingSenderId: '925046371887',
    projectId: 'translato-ac737',
    storageBucket: 'translato-ac737.appspot.com',
    iosBundleId: 'com.example.translato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTtYmGaU1V67UoLvoZpiKcBUz6ECeCgLI',
    appId: '1:925046371887:ios:659953cf11deab064178da',
    messagingSenderId: '925046371887',
    projectId: 'translato-ac737',
    storageBucket: 'translato-ac737.appspot.com',
    iosBundleId: 'com.example.translato.RunnerTests',
  );
}