// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAeQCLosKKUk9OZNai4uOgDZVZ3wczo0o',
    appId: '1:791812366023:web:da56927909681e2bbda8e2',
    messagingSenderId: '791812366023',
    projectId: 'translato-20d07',
    authDomain: 'translato-20d07.firebaseapp.com',
    storageBucket: 'translato-20d07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkypwAS4Wscsmd-ZTcxcDIPysvYQiMsI',
    appId: '1:791812366023:android:f815096308e6fd8dbda8e2',
    messagingSenderId: '791812366023',
    projectId: 'translato-20d07',
    storageBucket: 'translato-20d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEAFCfm3Aor-v7BL-tlUjnO-vKY9BBeo',
    appId: '1:791812366023:ios:5a5289988b2d6223bda8e2',
    messagingSenderId: '791812366023',
    projectId: 'translato-20d07',
    storageBucket: 'translato-20d07.appspot.com',
    iosBundleId: 'com.example.translato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgEAFCfm3Aor-v7BL-tlUjnO-vKY9BBeo',
    appId: '1:791812366023:ios:cb4aa4d4e542ff8abda8e2',
    messagingSenderId: '791812366023',
    projectId: 'translato-20d07',
    storageBucket: 'translato-20d07.appspot.com',
    iosBundleId: 'com.example.translato.RunnerTests',
  );
}
